### ISSUE TITLE
Nextcloud user name not set - exiting

### ISSUE THREAD

**Issue by PhiGi87** [boredazfcuk/docker-nextcloudcli#1]
After starting the error comes. But I have specified the USER Env:

`Thu Feb  3 14:22:37 2022 INFO:    ***** Starting Nexcloud CLI synchronisation container *****
Thu Feb  3 14:22:37 2022 INFO:    Alpine Linux v3.14
Thu Feb  3 14:22:37 2022 INFO:    Local user: user:1000
Thu Feb  3 14:22:37 2022 INFO:    Local group: group:1000
Thu Feb  3 14:22:37 2022 INFO:    Local directory: /home/user/Nextcloud
Thu Feb  3 14:22:37 2022 ERROR:   Nextcloud user name not set - exiting`

**Comment by boredazfcuk** [comment]
Sorry, my fault. I've not updated the README in a while to reflect changes I'd made to the variable names.

I've updated it now.
